#!perl
use strict;
use warnings;
use App::aki;

my $aki = App::aki->run(@ARGV);

__END__

=head1 NAME

aki - The command-line data processor for web content

=head1 SYNOPSIS

    $ aki [options] URL

=head2 OPTIONS

    -d   --decoder       specify deoder(default: auto detect)
         --agent         user agent
         --timeout       connection timeout
    -m,  --method        HTTP method(default: GET)
    -p,  --pointer       JSON pointer string(See: L<JSON::Pointer>)
    -ie, --in-encoding   input encoding
    -oe, --out-encoding  output encoding
         --color         colorize the result
         --raw           show raw content
         --verbose       show verbose information

    -h,  --help          show this help
    -v,  --version       show the version

=head2 EXAMPLE

    $ aki http://example.com/json --pointer '/foo/bar/0'
    ---
        baz     123
        qux     "foobar"
    ---

=head1 AUTHOR

Dai Okabayashi E<lt>bayashi@cpan.orgE<gt>


=head1 SEE ALSO

L<JSON::Pointer>


=head1 LICENSE

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself. See L<perlartistic>.


=cut
